import { getOrders, getSizes, getMetals, getStyles } from "./database.js"
const orders = getOrders()

// this function returns a list of ordesr with their id # and timestamp
const buildOrderListItem = (order) => {
    const metals = getMetals()
    // the function you pass to find() must return a boolean value /true/false
    const foundMetal = metals.find(
        (metal) => {
            return metal.id === order.metalId
        }
    )
    const sizes = getSizes()
    const foundSize = sizes.find(
        (size) => {
            return size.id === order.sizeId
        }
    )
    const styles = getStyles()
    const foundStyle = styles.find(
        (style) => {
            return style.id === order.styleId
        }
    )
    const totalCost = foundMetal.price + foundSize.price + foundStyle.price
    const costString = totalCost.toLocaleString("en-US", {
        style: "currency",
        currency: "USD"
    })

    return `<li>
        Order #${order.id} costs ${costString}`
}

export const Orders = () => {
    /*
    The timestamp within the orders function is necessary because this function is primarily made up of foreign keys that are generated by the user when choosing their custom jewelry options. 
    */
    const orders = getOrders()
    
    let html = "<ul>"

    const listItems = orders.map(buildOrderListItem)

    html += listItems.join("")
    html += "</ul>"

    return html
}

        